### ISSUE TITLE
New account creation, login, and guest/demo login

### ISSUE THREAD

**Issue by nicolaseschneider** [NicolasESchneider/Discoded#6]
- [ ] MVP is completely styled and seeded
- [ ] MVP is bug free with smooth navigation
- [ ] MVP is bug free on a hard refresh (⌘ + shift + R)
- [ ] MVP handles errors with informative messages for user

- [ ] splash page is animated
- [ ] drop-down menu works
- [ ] clicking the box triggers an animation.

**Comment by ssoonmi** [comment]
### Splash Page
- [ ] `Open Discoded In Browser` and `Sign Up` buttons are slightly off in styling. They are supposed to have more padding

### Logging In
- [ ] if I am logged in and I try to go to the splash page, at path: `/`, then a dummy component gets rendered instead of the home page or the server index page
